// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using Newtonsoft.Json;

namespace HabitRPG.NET.Models
{
    public class Task
    {

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("attribute")]
        public string Attribute { get; set; }

        [JsonProperty("priority")]
        public double Priority { get; set; }

        [JsonProperty("value")]
        public double Value { get; set; }

        [JsonProperty("tags")]
        [JsonConverter(typeof(TagsConverter))]
        public TaskTag[] Tags { get; set; }

        [JsonProperty("notes")]
        public string Notes { get; set; }

        [JsonProperty("dateCreated")]
        public DateTime DateCreated { get; set; }

        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("down")]
        public bool Down { get; set; }

        [JsonProperty("up")]
        public bool Up { get; set; }

        [JsonProperty("history")]
        public History[] History { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("streak")]
        public int? Streak { get; set; }

        [JsonProperty("checklist")]
        public Checklist[] Checklist { get; set; }

        [JsonProperty("collapseChecklist")]
        public bool? CollapseChecklist { get; set; }

        [JsonProperty("repeat")]
        public Repeat Repeat { get; set; }

        [JsonProperty("completed")]
        public bool? Completed { get; set; }

        [JsonProperty("dateCompleted")]
        public DateTime DateCompleted { get; set; }

        [JsonProperty("date")]
        public string Date { get; set; }
    }

}
